name: darman frontend continuous integration

on:
  push:
    branches: [ "master" ]
    paths:
      - 'public/**'
      - 'src/**'
      - '.env.production'
      - 'Dockerfile'
      - 'package.json'

jobs:
  build_and_push:
    name: Build image and push to registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Login to Docker Registery
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.numenoreans.com -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          docker build -t ${{ vars.IMAGE_ADDR }} .
          docker push ${{ vars.IMAGE_ADDR }}


  deploy:
    name: Deploy project on production
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: SSH server docker login
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          retries: 3
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login docker.numenoreans.com -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: SSH server update image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          retries: 3
          script: docker pull "${{ vars.IMAGE_ADDR }}"

      - name: SSH server update service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: n-services-update
